api setup

diff --git a/bin/insta485db b/bin/insta485db
--- a/bin/insta485db
+++ b/bin/insta485db
@@ -43,6 +43,33 @@ case $1 in
     sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM posts'
     sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM users'
     ;;
+
+  "random")
+  DB_FILENAME=var/insta485.sqlite3
+
+  if command -v magick &> /dev/null; then
+    IM_CMD="magick"
+  elif command -v convert &> /dev/null; then
+    IM_CMD="convert"
+  else
+    echo "Error: Neither 'magick' nor 'convert' command found."
+    exit 1
+  fi
+
+  for i in `seq 1 100`; do
+    FILENAME="$(uuidgen).png"
+    NUMS=()
+    for j in `seq 1 6`; do
+        NUMS+=($(($RANDOM % 255)))
+    done
+    "$IM_CMD" -size 360x360 \
+            radial-gradient:"rgb(${NUMS[0]},${NUMS[1]},${NUMS[2]})-rgb(${NUMS[3]},${NUMS[4]},${NUMS[5]})" \
+            -pointsize 64 -fill black -gravity center -annotate 0 "image $i" "var/uploads/$FILENAME"
+    OWNER="awdeorio"
+    sqlite3 -echo -batch ${DB_FILENAME} "INSERT INTO posts(filename, owner) VALUES('${FILENAME}','${OWNER}');"
+  done
+
+    ;;
   *)
     usage
     exit 1
